Add .clang-format with defaults matching what's specified in the style guide
There are two use cases for this .clang-format:

1. Local reformatting of source code, e.g. using Emacs clang-format.el package.
   This is basically a wawy to accelerate routine reformatting actions during
   heavy editing or refactoring.

2. Global reformatting of the source code, e.g. using the 'make reformat'
   rule in the 'build' makefiles.

Presently, our source code is not entirely ready for this kind of
refactoring yet, mostly because several of our headers are not
self-contained, so you end up with errors like:

    In file included from agent-msg-filter.c:25:
    In file included from ./red-common.h:37:
    In file included from ./spice.h:27:
    ./spice-migration.h:47:31: error: unknown type name 'SpiceServer'